services:
  nginx-guryn-ru:
    labels:
      - konta.managed=true
      - traefik.http.routers.nginx-guryn-ru.rule=Host(`nginx.guryn.ru`)
      - traefik.http.routers.nginx-guryn-ru.entrypoints=https
      - traefik.http.routers.nginx-guryn-ru.service=nginx-guryn-ru
      - traefik.http.services.nginx-guryn-ru.loadbalancer.server.port=80
      - traefik.http.routers.nginx-guryn-ru.tls=true
      - traefik.http.routers.nginx-guryn-ru.tls.certresolver=letsencrypt
    image: nginx:latest
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external: true
